# Required
version: 2

build:
  os: ubuntu-24.04
  tools:
    ruby: "3.3"

  commands:
    - gem install bundler
    - bundle install
    - mkdir Mabbs
    - curl -L -o Mabbs/README.md https://github.com/Mabbs/Mabbs/raw/main/README.md
    - bundle exec jekyll build --destination $READTHEDOCS_OUTPUT/html
    - tar czvf MayxBlog.tgz -C $READTHEDOCS_OUTPUT html
    - mv MayxBlog.tgz $READTHEDOCS_OUTPUT/html