theme: jekyll-theme-minimal
title: Mayx的博客
logo: /images/17966333.png
author: mayx
description: Mayx's Home Page
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
paginate: 7
plugins:
  - jekyll-sitemap
  - jekyll-feed
feed:
  path: atom.xml
google_analytics: UA-137710294-1
