theme: jekyll-theme-minimal
title: Mayx的博客
logo: https://avatars0.githubusercontent.com/u/17966333
lang: zh-CN
author: mayx
description: Mayx's Home Page
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
paginate: 7
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
feed:
  path: atom.xml
webmaster_verifications:
  google: huTYdEesm8NaFymixMNqflyCp6Jfvd615j5Wq1i2PHc
  yandex: fc0e535abed800be
  bing: 0ADFCE64B3557DC4DC5F2DC224C5FDDD
google_analytics: UA-137710294-1
