theme: jekyll-theme-minimal
title: Mayx的博客
logo: https://avatars0.githubusercontent.com/u/17966333
lang: zh-CN
author: mayx
description: Mayx's Home Page
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
paginate: 7
kramdown:
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
feed:
  path: atom.xml
google_analytics: UA-137710294-1
